on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Run Tox tests

jobs:
  tox_test:
    name: Tox test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11', '3.12' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install install tox tox-gh-actions --upgrade pip
      - name: Run tox tests
        run: tox